"$schema" = 'https://starship.rs/config-schema.json'

# ~/.config/starship.toml
format = """$env_var$os$username$hostname$directory$git_branch$git_status$python
$character
"""

right_format = "$kubernetes"

[kubernetes]
disabled = false
format = '[󱃾 ${context:0:6}\(${namespace}\)](bold cyan) '

